// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Captcha: typeof import('./src/components/common/Captcha.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FormDialog: typeof import('./src/components/common/FormDialog.vue')['default']
    HomeIndex: typeof import('./src/components/home/HomeIndex.vue')['default']
    HomeMain: typeof import('./src/components/home/HomeMain.vue')['default']
    HomeMenu: typeof import('./src/components/home/HomeMenu.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PermissionIndex: typeof import('./src/components/permission/PermissionIndex.vue')['default']
    PermissionList: typeof import('./src/components/permission/PermissionList.vue')['default']
    PermissionRole: typeof import('./src/components/permission/PermissionRole.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingIn: typeof import('./src/components/sing/SingIn.vue')['default']
    SingUp: typeof import('./src/components/sing/SingUp.vue')['default']
    TablePagination: typeof import('./src/components/common/TablePagination.vue')['default']
    TreeDialog: typeof import('./src/components/common/TreeDialog.vue')['default']
    UploadAvatarDialog: typeof import('./src/components/common/UploadAvatarDialog.vue')['default']
    UploadFileDialog: typeof import('./src/components/common/UploadFileDialog.vue')['default']
    UserIndex: typeof import('./src/components/user/UserIndex.vue')['default']
    UserList: typeof import('./src/components/user/UserList.vue')['default']
  }
}
